<?php

namespace AppBundle\Repository;

/**
 * TvShowAPIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowAPIRepository extends \Doctrine\ORM\EntityRepository
{
}
